/* Splats: Gaussian splat viewer for iPhone and iPad.
 *
 * Built on Windows/Linux/macOS without Xcode or the iOS SDK: plain C that talks
 * to UIKit and Metal through the Objective-C runtime. Everything it uses from
 * iOS is declared below; build_ios.py writes small .tbd files that tell the
 * linker which system library provides each symbol.
 *
 * The rendering itself is the HA++ code in gaussian/splat.ha: pack_splats()
 * (CPU) and ten GPU kernels whose Metal source is embedded in the library and
 * compiled on the device. Drag with one finger to orbit, pinch to zoom.
 */
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "splat.h"   /* generated by happ: structs, kernels' parameter structs, functions */

/* ------------------------------------------------------------------ iOS declarations */
typedef struct objc_object *id;
typedef struct objc_selector *SEL;
typedef struct objc_class *Class;
typedef void (*IMP)(void);
typedef unsigned long NSUInteger;
typedef long NSInteger;
typedef double CGFloat;
typedef struct { CGFloat x, y; } CGPoint;
typedef struct { CGFloat width, height; } CGSize;
typedef struct { CGPoint origin; CGSize size; } CGRect;
typedef struct { NSUInteger width, height, depth; } MTLSize;

extern void objc_msgSend(void);     /* never called directly: always cast to the real signature */
Class objc_getClass(const char *name);
SEL sel_registerName(const char *name);
Class objc_allocateClassPair(Class superclass, const char *name, size_t extra);
void objc_registerClassPair(Class cls);
bool class_addMethod(Class cls, SEL name, IMP imp, const char *types);
void *objc_autoreleasePoolPush(void);
void objc_autoreleasePoolPop(void *pool);

int UIApplicationMain(int argc, char **argv, id principal, id delegate_class_name);
id MTLCreateSystemDefaultDevice(void);
double CACurrentMediaTime(void);
/* The run-loop mode must be this very object: CoreFoundation compares it by address, and any
   other string called "kCFRunLoopCommonModes" becomes a separate mode that UIKit never runs. */
extern id const kCFRunLoopCommonModes;

typedef struct CGColorSpace *CGColorSpaceRef;
typedef struct CGDataProvider *CGDataProviderRef;
typedef struct CGImage *CGImageRef;
CGColorSpaceRef CGColorSpaceCreateDeviceRGB(void);
void CGColorSpaceRelease(CGColorSpaceRef cs);
CGDataProviderRef CGDataProviderCreateWithData(void *info, const void *data, size_t size,
                                               void (*release)(void *info, const void *data, size_t size));
void CGDataProviderRelease(CGDataProviderRef p);
CGImageRef CGImageCreate(size_t w, size_t h, size_t bits_per_component, size_t bits_per_pixel, size_t bytes_per_row,
                         CGColorSpaceRef cs, uint32_t bitmap_info, CGDataProviderRef p, const CGFloat *decode,
                         bool interpolate, int32_t intent);
void CGImageRelease(CGImageRef img);

typedef struct __sFILE FILE;
void *malloc(size_t n);
void free(void *p);
void *memcpy(void *d, const void *s, size_t n);
void *memset(void *d, int c, size_t n);
int snprintf(char *buf, size_t n, const char *fmt, ...);
FILE *fopen(const char *path, const char *mode);
size_t fread(void *p, size_t size, size_t n, FILE *f);
int fseek(FILE *f, long off, int whence);
long ftell(FILE *f);
int fclose(FILE *f);
double sin(double x);
double cos(double x);
double tan(double x);
double sqrt(double x);

/* ------------------------------------------------------------------ Objective-C helpers */
#define SEL_(s) sel_registerName(s)
#define MSG(ret, ...) ((ret(*)(__VA_ARGS__))objc_msgSend)

static id cls(const char *name) { return (id)objc_getClass(name); }
static id msg0(id o, const char *s) { return MSG(id, id, SEL)(o, SEL_(s)); }
static id msg1(id o, const char *s, id a) { return MSG(id, id, SEL, id)(o, SEL_(s), a); }
static void call0(id o, const char *s) { MSG(void, id, SEL)(o, SEL_(s)); }
static id nsstr(const char *s) { return MSG(id, id, SEL, const char *)(cls("NSString"), SEL_("stringWithUTF8String:"), s); }
static const char *cstr(id s) { return s ? MSG(const char *, id, SEL)(s, SEL_("UTF8String")) : ""; }
static id new_obj(const char *class_name) { return msg0(msg0(cls(class_name), "alloc"), "init"); }

/* ------------------------------------------------------------------ app state */
enum { K_PRE, K_SCAN_BLOCKS, K_SCAN_SUMS, K_SCAN_ADD, K_BIN, K_HIST, K_SCATTER, K_CLEAR, K_RANGES, K_RENDER, K_COUNT };
static const char *const KERNEL_NAMES[K_COUNT] = {"preprocess", "scan_blocks", "scan_sums", "scan_add", "bin",
                                                  "radix_hist", "radix_scatter", "clear", "ranges", "render"};
static const unsigned KERNEL_WG[K_COUNT] = {HA_PREPROCESS_WORKGROUP_X, HA_SCAN_BLOCKS_WORKGROUP_X,
                                            HA_SCAN_SUMS_WORKGROUP_X, HA_SCAN_ADD_WORKGROUP_X, HA_BIN_WORKGROUP_X,
                                            HA_RADIX_HIST_WORKGROUP_X, HA_RADIX_SCATTER_WORKGROUP_X,
                                            HA_CLEAR_WORKGROUP_X, HA_RANGES_WORKGROUP_X, HA_RENDER_WORKGROUP_X};

enum { B_SPLATS, B_CAMERA, B_PROJS, B_COUNTS, B_OFFSETS, B_SUMS, B_KEYS0, B_VALS0, B_KEYS1, B_VALS1, B_HIST, B_HSUMS,
       B_SPANS, B_IMAGE, B_COUNT };

static struct {
    id window, view, layer, label, link, delegate;
    id device, queue, pipes[K_COUNT];
    id bufs[B_COUNT];
    size_t caps[B_COUNT];
    uint32_t n;
    int width, height;
    CGFloat scale;
    double yaw, pitch, dist, last_touch;
    double frame_ms, fps_time;
    int frames;
    uint32_t pairs;
    bool ready;
    char status[512];
} app;

static void set_status(const char *text) {
    if (app.label) msg1(app.label, "setText:", nsstr(text));
}

/* ------------------------------------------------------------------ Metal renderer */
/* A GPU buffer of at least `bytes`. Buffers whose size changes every frame grow by 1.5x so that
   moving the camera doesn't reallocate them over and over. False (with a message) if out of memory. */
static bool buffer(int which, size_t bytes, bool grows) {
    if (bytes < 16) bytes = 16;
    if (app.bufs[which] && app.caps[which] >= bytes) return true;
    if (app.bufs[which]) call0(app.bufs[which], "release");
    size_t size = grows ? bytes + bytes / 2 : bytes;
    app.bufs[which] = MSG(id, id, SEL, NSUInteger, NSUInteger)(app.device, SEL_("newBufferWithLength:options:"),
                                                               (NSUInteger)size, 0 /* shared CPU/GPU memory */);
    app.caps[which] = app.bufs[which] ? size : 0;
    if (!app.bufs[which]) {
        snprintf(app.status, sizeof app.status, "Out of GPU memory (%lu MB buffer)", (unsigned long)(size >> 20));
        return false;
    }
    return true;
}

static void *contents(int which) { return MSG(void *, id, SEL)(app.bufs[which], SEL_("contents")); }

static const char *error_text(id err) {
    return err ? cstr(msg0(err, "localizedDescription")) : "unknown error";
}

static bool renderer_init(void) {
    app.device = MTLCreateSystemDefaultDevice();
    if (!app.device) {
        snprintf(app.status, sizeof app.status, "This device has no Metal GPU.");
        return false;
    }
    app.queue = msg0(app.device, "newCommandQueue");
    uint64_t size = 0;
    const char *source = splat_metal_source(&size);
    id err = 0;
    id library = MSG(id, id, SEL, id, id, id *)(app.device, SEL_("newLibraryWithSource:options:error:"),
                                               nsstr(source), (id)0, &err);
    if (!library) {
        snprintf(app.status, sizeof app.status, "Metal compile error:\n%s", error_text(err));
        return false;
    }
    for (int k = 0; k < K_COUNT; k++) {
        id fn = msg1(library, "newFunctionWithName:", nsstr(KERNEL_NAMES[k]));
        if (!fn) {
            snprintf(app.status, sizeof app.status, "Metal kernel missing: %s", KERNEL_NAMES[k]);
            return false;
        }
        err = 0;
        app.pipes[k] = MSG(id, id, SEL, id, id *)(app.device, SEL_("newComputePipelineStateWithFunction:error:"), fn,
                                                  &err);
        if (!app.pipes[k]) {
            snprintf(app.status, sizeof app.status, "Metal pipeline error (%s):\n%s", KERNEL_NAMES[k],
                     error_text(err));
            return false;
        }
    }
    return true;
}

static bool load_scene(void) {
    /* scene.bin (GaussianRaw records, made by build_ios.py --ply) if bundled, else a generated galaxy */
    id bundle = msg0(cls("NSBundle"), "mainBundle");
    id path = MSG(id, id, SEL, id, id)(bundle, SEL_("pathForResource:ofType:"), nsstr("scene"), nsstr("bin"));
    GaussianRaw *raw = 0;
    uint32_t n = 0;
    if (path) {
        FILE *f = fopen(cstr(path), "rb");
        if (f) {
            fseek(f, 0, 2 /* SEEK_END */);
            long bytes = ftell(f);
            fseek(f, 0, 0);
            n = (uint32_t)(bytes / (long)sizeof(GaussianRaw));
            raw = (GaussianRaw *)malloc((size_t)n * sizeof(GaussianRaw) + 1);
            if (raw && fread(raw, sizeof(GaussianRaw), n, f) != n) n = 0;
            fclose(f);
        }
    }
    if (n == 0) {
        n = 60000;
        free(raw);
        raw = (GaussianRaw *)malloc((size_t)n * sizeof(GaussianRaw));
        if (!raw) return false;
        make_galaxy(raw, n, 1);          /* HA++ code */
    }
    app.n = n;
    if (!buffer(B_SPLATS, (size_t)n * sizeof(PackedSplat), false)) {
        free(raw);
        return false;
    }
    pack_splats(raw, (PackedSplat *)contents(B_SPLATS), n);      /* HA++ code: 32 bytes per splat */
    free(raw);
    return buffer(B_CAMERA, sizeof(Camera), false) && buffer(B_PROJS, (size_t)n * sizeof(Proj), false) &&
           buffer(B_COUNTS, (size_t)n * 4, false) && buffer(B_OFFSETS, (size_t)n * 4, false) &&
           buffer(B_SUMS, 4 * (((size_t)n + 255) / 256), false);
}

static MTLSize groups1(size_t items, unsigned wg) {
    MTLSize s = {(items + wg - 1) / wg, 1, 1};
    if (s.width == 0) s.width = 1;
    return s;
}

static void dispatch(id enc, int k, const int *bufs, int nbuf, const void *params, size_t params_size, MTLSize groups,
                     MTLSize threads) {
    msg1(enc, "setComputePipelineState:", app.pipes[k]);
    for (int i = 0; i < nbuf; i++)
        MSG(void, id, SEL, id, NSUInteger, NSUInteger)(enc, SEL_("setBuffer:offset:atIndex:"), app.bufs[bufs[i]], 0,
                                                       (NSUInteger)i);
    if (params_size)
        MSG(void, id, SEL, const void *, NSUInteger, NSUInteger)(enc, SEL_("setBytes:length:atIndex:"), params,
                                                                 (NSUInteger)params_size, (NSUInteger)nbuf);
    MSG(void, id, SEL, MTLSize, MTLSize)(enc, SEL_("dispatchThreadgroups:threadsPerThreadgroup:"), groups, threads);
}

static void dispatch1(id enc, int k, const int *bufs, int nbuf, const void *params, size_t params_size,
                      size_t items) {
    MTLSize threads = {KERNEL_WG[k], 1, 1};
    dispatch(enc, k, bufs, nbuf, params, params_size, groups1(items, KERNEL_WG[k]), threads);
}

static void scan(id enc, int data, uint32_t count, int sums) {
    uint32_t nb = (count + 255) / 256;
    ha_params_scan_blocks pb = {count};
    ha_params_scan_sums ps = {nb};
    ha_params_scan_add pa = {count};
    int b1[] = {data, sums}, b2[] = {sums};
    dispatch1(enc, K_SCAN_BLOCKS, b1, 2, &pb, sizeof pb, count);
    MTLSize one = {1, 1, 1}, wg = {HA_SCAN_SUMS_WORKGROUP_X, 1, 1};
    dispatch(enc, K_SCAN_SUMS, b2, 1, &ps, sizeof ps, one, wg);
    dispatch1(enc, K_SCAN_ADD, b1, 2, &pa, sizeof pa, count);
}

static bool run(id cmd) {
    call0(cmd, "commit");
    call0(cmd, "waitUntilCompleted");
    id err = msg0(cmd, "error");
    if (err) {
        /* e.g. work submitted while the app goes to the background: skip this frame, try the next one */
        snprintf(app.status, sizeof app.status, "GPU error (will retry): %s", error_text(err));
        set_status(app.status);
        return false;
    }
    return true;
}

/* world -> camera (x right, y down, z forward), column-major, orbiting the scene center */
static void camera_matrix(float *view) {
    double cy = cos(app.yaw), sy = sin(app.yaw), cp = cos(app.pitch), sp = sin(app.pitch);
    double eye[3] = {app.dist * cp * sy, app.dist * sp, -app.dist * cp * cy};
    double f[3] = {-eye[0], -eye[1], -eye[2]};
    double fl = sqrt(f[0] * f[0] + f[1] * f[1] + f[2] * f[2]);
    for (int i = 0; i < 3; i++) f[i] /= fl;
    double r[3] = {f[1] * 0.0 - f[2] * 1.0, f[2] * 0.0 - f[0] * 0.0, f[0] * 1.0 - f[1] * 0.0};   /* f x up */
    double rl = sqrt(r[0] * r[0] + r[1] * r[1] + r[2] * r[2]);
    for (int i = 0; i < 3; i++) r[i] /= rl;
    double d[3] = {f[1] * r[2] - f[2] * r[1], f[2] * r[0] - f[0] * r[2], f[0] * r[1] - f[1] * r[0]};   /* f x r */
    const double *rows[3] = {r, d, f};
    memset(view, 0, 16 * sizeof(float));
    for (int row = 0; row < 3; row++) {
        for (int col = 0; col < 3; col++) view[col * 4 + row] = (float)rows[row][col];
        view[12 + row] = (float)-(rows[row][0] * eye[0] + rows[row][1] * eye[1] + rows[row][2] * eye[2]);
    }
    view[15] = 1.0f;
}

static void free_pixels(void *info, const void *data, size_t size) {
    (void)info;
    (void)size;
    free((void *)data);
}

#define MAX_PAIRS (8u << 20)        /* about 170 MB of sort buffers */
#define MIN_DIST 2.0

static void render_frame(void) {
    const uint32_t n = app.n;
    const int w = app.width, h = app.height;
    const uint32_t tiles_x = (uint32_t)(w + 15) / 16, tiles_y = (uint32_t)(h + 15) / 16;
    double t0 = CACurrentMediaTime();

    Camera *cam = (Camera *)contents(B_CAMERA);
    float view[16];
    camera_matrix(view);
    memcpy(&cam->view, view, sizeof view);
    float focal = (float)(0.5 * h / tan(0.5 * 60.0 * 3.14159265358979 / 180.0));
    cam->focal.x = focal;
    cam->focal.y = focal;
    cam->center.x = 0.5f * (float)w;
    cam->center.y = 0.5f * (float)h;
    cam->size.x = (float)w;
    cam->size.y = (float)h;
    cam->near = 0.05f;
    cam->far = 100.0f;
    cam->tiles_x = tiles_x;
    cam->tiles_y = tiles_y;

    /* phase A: project splats, prefix sum of the tiles they touch */
    id cmd = msg0(app.queue, "commandBuffer");
    id enc = msg0(cmd, "computeCommandEncoder");
    ha_params_preprocess pp = {n};
    int bpre[] = {B_SPLATS, B_CAMERA, B_PROJS, B_COUNTS, B_OFFSETS};
    dispatch1(enc, K_PRE, bpre, 5, &pp, sizeof pp, n);
    scan(enc, B_OFFSETS, n, B_SUMS);
    call0(enc, "endEncoding");
    if (!run(cmd)) return;
    const uint32_t *offsets = (const uint32_t *)contents(B_OFFSETS);
    const uint32_t *counts = (const uint32_t *)contents(B_COUNTS);
    uint32_t total = n ? offsets[n - 1] + counts[n - 1] : 0;
    app.pairs = total;

    if (total > MAX_PAIRS) {
        /* every (splat, tile) pair costs about 20 bytes and sorting time: keep the last image */
        snprintf(app.status, sizeof app.status, "Too close: %u tile pairs (limit %u).\nPinch out.", total,
                 (unsigned)MAX_PAIRS);
        set_status(app.status);
        app.fps_time = CACurrentMediaTime();
        app.frames = 0;
        return;
    }

    /* phase B: bin, radix sort, tile ranges, render */
    uint32_t ntiles = tiles_x * tiles_y, nb = total ? (total + 255) / 256 : 1;
    if (!(buffer(B_KEYS0, (size_t)total * 4, true) && buffer(B_VALS0, (size_t)total * 4, true) &&
          buffer(B_KEYS1, (size_t)total * 4, true) && buffer(B_VALS1, (size_t)total * 4, true) &&
          buffer(B_HIST, (size_t)256 * nb * 4, true) && buffer(B_HSUMS, (size_t)nb * 4, true) &&
          buffer(B_SPANS, (size_t)ntiles * 8, true) && buffer(B_IMAGE, (size_t)w * h * 4, true))) {
        set_status(app.status);
        return;
    }
    cmd = msg0(app.queue, "commandBuffer");
    enc = msg0(cmd, "computeCommandEncoder");
    if (total) {
        ha_params_bin pbin = {n, tiles_x};
        int bbin[] = {B_PROJS, B_OFFSETS, B_COUNTS, B_KEYS0, B_VALS0};
        dispatch1(enc, K_BIN, bbin, 5, &pbin, sizeof pbin, n);
        int src_k = B_KEYS0, src_v = B_VALS0, dst_k = B_KEYS1, dst_v = B_VALS1;
        for (uint32_t shift = 0; shift < 32; shift += 8) {
            ha_params_radix_hist ph = {total, shift, nb};
            ha_params_radix_scatter psc = {total, shift, nb};
            int bh[] = {src_k, B_HIST};
            int bs[] = {src_k, src_v, dst_k, dst_v, B_HIST};
            dispatch1(enc, K_HIST, bh, 2, &ph, sizeof ph, total);
            scan(enc, B_HIST, 256 * nb, B_HSUMS);
            dispatch1(enc, K_SCATTER, bs, 5, &psc, sizeof psc, total);
            int tk = src_k, tv = src_v;
            src_k = dst_k;
            src_v = dst_v;
            dst_k = tk;
            dst_v = tv;
        }
    }
    ha_params_clear pc = {2 * ntiles};
    int bclear[] = {B_SPANS};
    dispatch1(enc, K_CLEAR, bclear, 1, &pc, sizeof pc, 2 * ntiles);
    if (total) {
        ha_params_ranges pr = {total};
        int br[] = {B_KEYS0, B_SPANS};
        dispatch1(enc, K_RANGES, br, 2, &pr, sizeof pr, total);
    }
    ha_params_render prend = {(uint32_t)w, (uint32_t)h, 0xFF160A08u};
    int brend[] = {B_PROJS, B_VALS0, B_SPANS, B_IMAGE};
    MTLSize tiles = {tiles_x, tiles_y, 1}, tile_threads = {HA_RENDER_WORKGROUP_X, HA_RENDER_WORKGROUP_Y, 1};
    dispatch(enc, K_RENDER, brend, 4, &prend, sizeof prend, tiles, tile_threads);
    call0(enc, "endEncoding");
    if (!run(cmd)) return;

    /* show the image: copy it into a CGImage (the GPU buffer is reused next frame) */
    size_t bytes = (size_t)w * h * 4;
    void *pixels = malloc(bytes);
    if (!pixels) return;
    memcpy(pixels, contents(B_IMAGE), bytes);
    CGColorSpaceRef cs = CGColorSpaceCreateDeviceRGB();
    CGDataProviderRef dp = CGDataProviderCreateWithData(0, pixels, bytes, free_pixels);
    CGImageRef img = CGImageCreate((size_t)w, (size_t)h, 8, 32, (size_t)w * 4, cs, 5 /* NoneSkipLast */, dp, 0, false,
                                   0);
    msg1(app.layer, "setContents:", (id)img);
    CGImageRelease(img);
    CGDataProviderRelease(dp);
    CGColorSpaceRelease(cs);

    double dt = (CACurrentMediaTime() - t0) * 1000.0;
    app.frame_ms = app.frame_ms ? 0.9 * app.frame_ms + 0.1 * dt : dt;
    app.frames++;
    double now = CACurrentMediaTime();
    if (now - app.fps_time > 0.5) {
        snprintf(app.status, sizeof app.status, "HA++ Gaussian splats\n%u splats, %u tile pairs, %dx%d\n%.1f ms/frame, %.0f fps",
                 app.n, app.pairs, w, h, app.frame_ms, app.frames / (now - app.fps_time));
        set_status(app.status);
        app.fps_time = now;
        app.frames = 0;
    }
}

/* ------------------------------------------------------------------ UIKit callbacks */
/* Render size follows the view: rotation, iPad Split View and Stage Manager change it. */
static void fit_to_view(void) {
    CGRect b = MSG(CGRect, id, SEL)(app.view, SEL_("bounds"));
    int w = (int)(b.size.width * app.scale / 2), h = (int)(b.size.height * app.scale / 2);  /* half resolution */
    if (w < 16) w = 16;
    if (h < 16) h = 16;
    if (w == app.width && h == app.height) return;
    app.width = w;
    app.height = h;
    CGRect label_frame = {{16, 48}, {b.size.width - 32, 72}};
    MSG(void, id, SEL, CGRect)(app.label, SEL_("setFrame:"), label_frame);
}

static void on_tick(id self, SEL cmd, id link) {
    (void)self;
    (void)cmd;
    (void)link;
    if (!app.ready) return;
    fit_to_view();
    if (CACurrentMediaTime() - app.last_touch > 2.0) app.yaw += 0.004;     /* slow automatic orbit */
    render_frame();
}

static void on_pan(id self, SEL cmd, id gesture) {
    (void)self;
    (void)cmd;
    CGPoint t = MSG(CGPoint, id, SEL, id)(gesture, SEL_("translationInView:"), app.view);
    app.yaw -= t.x * 0.006;
    app.pitch += t.y * 0.006;
    if (app.pitch > 1.45) app.pitch = 1.45;
    if (app.pitch < -1.45) app.pitch = -1.45;
    CGPoint zero = {0, 0};
    MSG(void, id, SEL, CGPoint, id)(gesture, SEL_("setTranslation:inView:"), zero, app.view);
    app.last_touch = CACurrentMediaTime();
}

static void on_pinch(id self, SEL cmd, id gesture) {
    (void)self;
    (void)cmd;
    CGFloat s = MSG(CGFloat, id, SEL)(gesture, SEL_("scale"));
    if (s > 0.01) app.dist /= s;
    if (app.dist < MIN_DIST) app.dist = MIN_DIST;
    if (app.dist > 30.0) app.dist = 30.0;
    MSG(void, id, SEL, CGFloat)(gesture, SEL_("setScale:"), 1.0);
    app.last_touch = CACurrentMediaTime();
}

/* Metal refuses work from the background: stop the frame loop while the app isn't active. */
static void will_resign_active(id self, SEL cmd, id application) {
    (void)self;
    (void)cmd;
    (void)application;
    if (app.link) MSG(void, id, SEL, bool)(app.link, SEL_("setPaused:"), true);
}

static void did_become_active(id self, SEL cmd, id application) {
    (void)self;
    (void)cmd;
    (void)application;
    if (app.link) MSG(void, id, SEL, bool)(app.link, SEL_("setPaused:"), false);
    app.fps_time = CACurrentMediaTime();
    app.frames = 0;
}

static id delegate_window(id self, SEL cmd) {
    (void)self;
    (void)cmd;
    return app.window;
}

static bool did_finish_launching(id self, SEL cmd, id application, id options) {
    (void)cmd;
    (void)options;
    id screen = msg0(cls("UIScreen"), "mainScreen");
    CGRect bounds = MSG(CGRect, id, SEL)(screen, SEL_("bounds"));
    CGFloat scale = MSG(CGFloat, id, SEL)(screen, SEL_("scale"));
    app.window = MSG(id, id, SEL, CGRect)(msg0(cls("UIWindow"), "alloc"), SEL_("initWithFrame:"), bounds);
    id vc = new_obj("UIViewController");
    msg1(app.window, "setRootViewController:", vc);
    call0(app.window, "makeKeyAndVisible");
    app.view = msg0(vc, "view");
    msg1(app.view, "setBackgroundColor:", msg0(cls("UIColor"), "blackColor"));
    app.layer = msg0(app.view, "layer");
    msg1(app.layer, "setContentsGravity:", nsstr("resizeAspectFill"));
    MSG(void, id, SEL, bool)(application, SEL_("setIdleTimerDisabled:"), true);

    CGRect label_frame = {{16, 48}, {bounds.size.width - 32, 72}};
    app.label = MSG(id, id, SEL, CGRect)(msg0(cls("UILabel"), "alloc"), SEL_("initWithFrame:"), label_frame);
    msg1(app.label, "setTextColor:", msg0(cls("UIColor"), "whiteColor"));
    msg1(app.label, "setFont:", MSG(id, id, SEL, CGFloat)(cls("UIFont"), SEL_("systemFontOfSize:"), 12.0));
    MSG(void, id, SEL, NSInteger)(app.label, SEL_("setNumberOfLines:"), 0);
    msg1(app.view, "addSubview:", app.label);

    id pan = MSG(id, id, SEL, id, SEL)(msg0(cls("UIPanGestureRecognizer"), "alloc"), SEL_("initWithTarget:action:"),
                                       self, SEL_("pan:"));
    msg1(app.view, "addGestureRecognizer:", pan);
    id pinch = MSG(id, id, SEL, id, SEL)(msg0(cls("UIPinchGestureRecognizer"), "alloc"),
                                         SEL_("initWithTarget:action:"), self, SEL_("pinch:"));
    msg1(app.view, "addGestureRecognizer:", pinch);

    /* render at half the screen's pixel resolution: plenty for splats, 4x less work */
    app.scale = scale;
    app.width = (int)(bounds.size.width * scale / 2);
    app.height = (int)(bounds.size.height * scale / 2);
    app.fps_time = CACurrentMediaTime();
    app.dist = 5.5;
    app.pitch = 0.6;
    app.yaw = 0.0;
    set_status("HA++ Gaussian splats: starting...");
    if (renderer_init() && load_scene()) {
        app.ready = true;
    } else {
        if (!app.status[0]) snprintf(app.status, sizeof app.status, "Could not load the scene.");
        set_status(app.status);
    }
    app.link = MSG(id, id, SEL, id, SEL)(cls("CADisplayLink"), SEL_("displayLinkWithTarget:selector:"), self,
                                         SEL_("tick:"));
    MSG(void, id, SEL, NSInteger)(app.link, SEL_("setPreferredFramesPerSecond:"), 60);
    MSG(void, id, SEL, id, id)(app.link, SEL_("addToRunLoop:forMode:"), msg0(cls("NSRunLoop"), "mainRunLoop"),
                               kCFRunLoopCommonModes);
    return true;
}

int main(int argc, char **argv) {
    void *pool = objc_autoreleasePoolPush();
    Class delegate = objc_allocateClassPair(objc_getClass("UIResponder"), "HASplatAppDelegate", 0);
    class_addMethod(delegate, SEL_("application:didFinishLaunchingWithOptions:"), (IMP)did_finish_launching, "B@:@@");
    class_addMethod(delegate, SEL_("window"), (IMP)delegate_window, "@@:");
    class_addMethod(delegate, SEL_("tick:"), (IMP)on_tick, "v@:@");
    class_addMethod(delegate, SEL_("pan:"), (IMP)on_pan, "v@:@");
    class_addMethod(delegate, SEL_("pinch:"), (IMP)on_pinch, "v@:@");
    class_addMethod(delegate, SEL_("applicationWillResignActive:"), (IMP)will_resign_active, "v@:@");
    class_addMethod(delegate, SEL_("applicationDidBecomeActive:"), (IMP)did_become_active, "v@:@");
    objc_registerClassPair(delegate);
    id name = nsstr("HASplatAppDelegate");
    int rc = UIApplicationMain(argc, argv, (id)0, name);
    objc_autoreleasePoolPop(pool);
    return rc;
}
